// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package modelo;

/************************************************************/
/**
 * 
 */
public class Alquiler {
	/**
	 * 
	 */
	private String DNI;
	/**
	 * 
	 */
	private String nombre;
	/**
	 * 
	 */
	private int tfno;
	/**
	 * 
	 */
	private String correo;
	/**
	 * 
	 */
	private Date fecha_nac;
	/**
	 * 
	 */
	private String contrasenya;
	/**
	 * 
	 */
	private Cliente cliente;
	/**
	 * 
	 */
	private Vehiculo vehiculo;
	/**
	 * 
	 */
	private EDate fecha_ini;
	/**
	 * 
	 */
	private EDate fecha_fin;
	/**
	 * 
	 */
	private EDouble total;
	/**
	 * 
	 */
	public DbCliente cliente;
	/**
	 * 
	 */
	public Vehiculo vehiculo;

	/**
	 * 
	 */
	public void resgistrar() {
	}

	/**
	 * 
	 */
	public void editar() {
	}

	/**
	 * 
	 */
	public void mostrar() {
	}

	/**
	 * 
	 */
	public void alquilar() {
	}

	/**
	 * 
	 */
	public void Alquiler() {
	}

	/**
	 * 
	 */
	public void editar() {
	}

	/**
	 * 
	 */
	public void mostrar() {
	}
}
