// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package modelo;

public class Cliente {
	private final String DNI;
	private String nombre;
	private int tfno;
	private String correo;
	private String direccion;

	public Cliente(String dNI, String nombre, int tfno, String correo, String direccion) {
		super();
		DNI = dNI;
		this.nombre = nombre;
		this.tfno = tfno;
		this.correo = correo;
		this.direccion = direccion;
	}

	public void editar() {
	}

	public void mostrar() {
	}

	public String getDNI() {
		return DNI;
	}


	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public int getTfno() {
		return tfno;
	}

	public void setTfno(int tfno) {
		this.tfno = tfno;
	}

	public String getCorreo() {
		return correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public String getDireccion() {
		return direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}
}
