// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package modelo;

public class Empleado {

	private String DNI;
	private String nombre;
	private String tfno;
	private String correo;
	private String direccion;
	private String contrasenya;
	private String rol;
	
	public void registrar() {
	}

	public void editar() {
	}

	public void mostrar() {
	}

	public void iniciarsesion() {
	}
}
