// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Diagrama.modelo;

/************************************************************/
/**
 * 
 */
public class Empleado {
	/**
	 * 
	 */
	private String DNI;
	/**
	 * 
	 */
	private String nombre;
	/**
	 * 
	 */
	private int tfno;
	/**
	 * 
	 */
	private String correo;
	/**
	 * 
	 */
	private EDate direccion;
	/**
	 * 
	 */
	private String contrasenya;
	/**
	 * 
	 */
	private String rol;

	/**
	 * 
	 */
	public void registrar() {
	}

	/**
	 * 
	 */
	public void editar() {
	}

	/**
	 * 
	 */
	public void mostrar() {
	}

	/**
	 * 
	 */
	public void iniciarsesion() {
	}
}
