// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package modelo;

/************************************************************/
/**
 * 
 */
public class Furgoneta extends Vehiculo {
	/**
	 * 
	 */
	private String tipo;
}
