// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package Diagrama.modelo;

/************************************************************/
/**
 * 
 */
public class Turismo extends Vehiculo {
	/**
	 * 
	 */
	private String tipo;
}
