// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package modelo;

/************************************************************/
/**
 * 
 */
public class Usuario {
	private final String DNI;
	private String nombre;
	private String tfno;
	private String correo;
	private String direccion;
	private String contrasea;

	public Usuario(String dNI, String nombre, String tfno, String correo, String direccion, String contrasea) {
		super();
		DNI = dNI;
		this.nombre = nombre;
		this.tfno = tfno;
		this.correo = correo;
		this.direccion = direccion;
		this.contrasea = contrasea;
	}

	public String getNombre() {
		return nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getTfno() {
		return tfno;
	}

	public void setTfno(String tfno) {
		this.tfno = tfno;
	}

	public String getCorreo() {
		return correo;
	}

	public void setCorreo(String correo) {
		this.correo = correo;
	}

	public String getDireccion() {
		return direccion;
	}

	public void setDireccion(String direccion) {
		this.direccion = direccion;
	}

	public String getContrasea() {
		return contrasea;
	}

	public void setContrasea(String contrasea) {
		this.contrasea = contrasea;
	}

	public String getDNI() {
		return DNI;
	}
	

}
<<<<<<< Updated upstream
=======

>>>>>>> Stashed changes
