// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package bdd;

/************************************************************/
/**
 * 
 */
public class DbAlquileres {
	/**
	 * 
	 */
	public void getAlquiler() {
	}

	/**
	 * 
	 */
	public void crearAlquiler() {
	}

	/**
	 * 
	 */
	public void eliminarAlquiler() {
	}

	/**
	 * 
	 */
	public void editarAlquiler() {
	}

	/**
	 * 
	 */
	public void consultarHistorial() {
	}
}
