// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package bdd;

import java.sql.PreparedStatement;
import java.sql.SQLException;

import modelo.Cliente;

public class DbCliente extends Conexion{
	public DbCliente() throws SQLException {
		super();
	}

	public boolean crearCliente(Cliente cliente) {
		String sql = "INSERT INTO usuario (dni, nombre, telef, correo, direccion, rol) VALUES (?, ?, ?, ?, ?, 'cliente')";

		
        try (PreparedStatement stmt = conexion.prepareStatement(sql)) {
            stmt.setString(1, cliente.getNombre());
            stmt.setString(2, cliente.getDNI());
            stmt.setString(3, cliente.getDireccion());
            stmt.setInt(4, cliente.getTfno());
            stmt.setString(5, cliente.getCorreo());
            int filas = stmt.executeUpdate();
            return filas > 0;
        } catch (SQLException e) {
            e.printStackTrace();
            return false;
        }		
	}


	public void eliminarCliente() {
	}

	public void editarDatosCliente() {
	}

	public void getCliente() {
	}
}
