// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package bdd;

/************************************************************/
/**
 * 
 */
public class DbUsuario {
	/**
	 * 
	 */
	public void iniciarSesion() {
	}

	/**
	 * 
	 */
	public void crearEmpleado() {
	}

	/**
	 * 
	 */
	public void eliminarEmpleado() {
	}

	/**
	 * 
	 */
	public void editarDatosEmpleado() {
	}

	/**
	 * 
	 */
	public void getEmpleado() {
	}
}
