// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package bdd;


import java.sql.PreparedStatement;
import java.sql.SQLException;

import modelo.Usuario;


/************************************************************/
/**
 * 
 */
//--------------------------------------------------------
//Code generated by Papyrus Java
//--------------------------------------------------------

import java.sql.PreparedStatement;
import java.sql.SQLException;

import modelo.Usuario;

public class DbUsuario extends Conexion{
	public DbUsuario() throws SQLException {
		super();
	}
		
	public boolean crearUsuario(Usuario usuario) {
		String sql = "INSERT INTO usuario (dni, nombre, telef, correo, direccion, contrasea, rol) VALUES (?, ?, ?, ?, ?, ?, ?)";	

     try (PreparedStatement stmt = conexion.prepareStatement(sql)) {
         stmt.setString(1, usuario.getNombre());
         stmt.setString(2, usuario.getDNI());
         stmt.setString(3, usuario.getDireccion());
         stmt.setString(4, usuario.getTfno());
         stmt.setString(5, usuario.getCorreo());
         stmt.setString(6, usuario.getContrasea());
         stmt.setString(7, usuario.getRol());
         int filas = stmt.executeUpdate();
         return filas > 0;
     } catch (SQLException e) {
         e.printStackTrace();
         return false;
     	}

	}
	/**
	 * 
	 */
	public void eliminarEmpleado() {
	}

	/**
	 * 
	 */
	public void editarDatosEmpleado() {
	}

	/**
	 * 
	 */
	public void getEmpleado() {
	}
}


