// --------------------------------------------------------
// Code generated by Papyrus Java
// --------------------------------------------------------

package bdd;

/************************************************************/
/**
 * 
 */
public class DbVehiculo {
	/**
	 * 
	 */
	public void getVehiculo() {
	}

	/**
	 * 
	 */
	public void crearVehiculo() {
	}

	/**
	 * 
	 */
	public void eliminarVehiculo() {
	}

	/**
	 * 
	 */
	public void editarVehiculo() {
	}

	/**
	 * 
	 */
	public void calMantenimiento() {
	}

	/**
	 * 
	 */
	public void consultarDisponibilidad() {
	}
}
